### PR TITLE
feat: as foundry now supports .env let's copy .env.example to .env [RFC]

### PR DESCRIPTION
**Pull request by sakulstra**
For this to work the assumption is that .env-contains reasonable defaults

### CODE REVIEW

**Comment by kyzia551** [comment]
Are you sure that it's a good assumption? Usually we have empty RPC URL in env.example

**Comment by sakulstra** [comment]
@kyzia551 i'm not that's why i didn't just merge :), it's up to discussion.

I think it kinda makes sense to have sensible defaults (why not add a public rpc in the example when it's needed to run the tests?) - especially with x-chain testing where you might need 2-n different rpcs it might make sense to just add it to the example like here https://github.com/bgd-labs/aave-v3-crosschain-listing-template/pull/8/files#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8cR5 ... soon one might also need optimism and arbitrum.

But yah i'm not 100% convinced either, but also don't have a better idea.
The alternative would be to setup secrets on all repos and use them as env inputs on each repo which also is cumbersome? Idk.

**Comment by sakulstra** [comment]
appendix to what i wrote above:

The alternative would be to require projects using this action to set `env` in the yaml.

In theory we could setup rpc secrets at the org level so actions would just need to do `RPC_OPTIMISM: ${{ secrets.RPC_OPTIMISM }}` and similar and we wouldn't need to set them up on each repo.

For other envs like blocknumber and so on it might still be cumbersome to maintain them via yml - in theory we could have both i guess?

**Comment by sakulstra** [comment]
Setting env does not actually work on shared workflows https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations

One thing could be to [inherit secrets](https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow) and set the env based on org level secrets ... seems a bit complex. As long as we don't need this i would just vote for merging this one and increase complexity as we see fit.

**Pull request merged**
